### PR TITLE
[502] added dynamic map

### LINKED ISSUE #502: As a user I want to be able to hide the dynamic map so i can view more properties on the Explore page
At the moment there is only a single view on the Explore page - property cards and a dynamic map.
We received a signal form the community that they would like to view more properties in the explore page (similar to the different views in opensea).
Therefore we need to add a view where the dynamic map is hidden (for Decentraland). This view will also enable the generic integration of other metaverses as not all of them will support a dynamic map.

Design is [here](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=8288%3A18778).

Basically we need to add:
- label indicating how many properties are currently showed (same number as the label in the header)
- icons for changing the view

The expected functionality:
- Icons will be to switch view (with and without map) when clicked.
- Icon with active view should be highlighted.
- For generic metaverse integration - no map view would be the default one and the map view would be inactive.

AC1: Given I want to view more properties on the Explore Page, when i click the view icon then the dynamic map will hide and I will see more properties on the page.
AC2: Given I have selected a generic metaverse, then the default view on the Explore Page is the one without a map and the dynamic map icon is inactive.

### PR DESCRIPTION
**Pull request by mishaadzh**
**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #502 

**Special notes for your reviewer**:

**Checklist**
- [x] Dynamic map

### CODE REVIEW

**Review by failfmi — DISMISSED** [review]

**Comment by failfmi** [comment]
By the way, in the issue it says that when the map is hidden, more properties have to be visualised, but here we have again 3 per row.

**Comment by failfmi** [comment]
In explore, if the metaverse selected is != `Decentraland` (you can compare it to `1`), we must not be able to show the map.

**Comment by mishaadzh** [comment]
> In explore, if the metaverse selected is != `Decentraland` (you can compare it to `1`), we must not be able to show the map.

Do we also have to hide the buttons when metaverse != `Decentraland`

**Comment by failfmi** [comment]
> > In explore, if the metaverse selected is != `Decentraland` (you can compare it to `1`), we must not be able to show the map.
> 
> @failfmi Do we also have to hide the buttons when metaverse != `Decentraland`

Whichever you find easier: disabled or hidden

**Review by failfmi — APPROVED** [review]

**Pull request merged**
