### PR TITLE
[233] refactoring header buttons

### PR DESCRIPTION
**Pull request by xdemocle**
Closes: #233

### CODE REVIEW

**Comment by xdemocle** [comment]
Meanwhile you guys reviews, im doing some more refactoring of CSS for using theme var instead of direct hexadecimal colors.

**Review by mishaadzh — APPROVED** [review]

**Comment by xdemocle** [comment]
done with css refactoring. all good

**Comment by failfmi** [comment]
image

**Comment by failfmi** [comment]
To be able to see the buttons you can either:
* list a property; rent it with another address (metamask account) and see the delist button
or
* change the visibility in the code and later return it back

**Comment by xdemocle** [comment]
> image

uhmmmm I should be able to emulate that button in position. let me check why the button gets so wide. I suspect the previous implementation was showing a popup from the inside the button lol

**Comment by failfmi** [comment]
> > image
> 
> uhmmmm I should be able to emulate that button in position. let me check why the button gets so wide. I suspect the previous implementation was showing a popup from the inside the button lol

The message is shown when the button is disabled & hovered (`You are configured as consumer of the property....`)

**Comment by xdemocle** [comment]
@failfmi all fixed. you can review and approve

**Comment by failfmi** [comment]
image
There's some bug with the hovering. If I remove the cursor from the mid left, the hover message stays.

**Comment by failfmi** [comment]
image

**Comment by failfmi** [comment]
image

**Comment by failfmi** [comment]
I think that `delist` and `withdraw` buttons should not have not background style, only `edit` & `stake`.

**Comment by xdemocle** [comment]
@failfmi okay, check now. Should be fine now. including the hovering issue that disappeared once I converted withdraw to same design of delist.

**Comment by failfmi** [comment]
Currently, delist:
image

**Pull request merged**
